/** Opens Gmail compose in a new tab with subject and body prefilled. */
export function openGmailCompose(options: { subject?: string; body: string; to?: string }) {
  const { subject = 'Atlas summary', body, to = '' } = options;
  const params = new URLSearchParams({
    view: 'cm',
    fs: '1',
  });
  if (to) params.set('to', to);
  if (subject) params.set('su', subject);
  if (body) params.set('body', body);
  const url = `https://mail.google.com/mail/?${params.toString()}`;
  window.open(url, '_blank', 'noopener,noreferrer');
}

/** Plain-text body suitable for email (strips minimal markdown noise). */
export function formatBodyForEmail(body: string, extras?: { citations?: string[]; uncertainty?: string | null }) {
  const lines = [body.trim()];
  if (extras?.citations?.length) {
    lines.push('', 'Sources: ' + extras.citations.join(', '));
  }
  if (extras?.uncertainty?.trim()) {
    lines.push('', 'Uncertainty flags:', extras.uncertainty.trim());
  }
  lines.push('', '—', 'Generated by Atlas (evidence-grounded product intelligence)');
  return lines.join('\n');
}
